<?php
/**
 * install_database.php
 * Création automatique de la base PostgreSQL
 */

date_default_timezone_set('Africa/Porto-Novo');

$host = getenv('DB_HOST');
$port = getenv('DB_PORT') ?: 5432;
$dbname = getenv('DB_NAME');
$user = getenv('DB_USER');
$password = getenv('DB_PASSWORD');

$logDir = __DIR__ . '/logs';

// if (!is_dir($logDir)) {
//     mkdir($logDir, 0777, true);
// }

$logFile = $logDir . '/database.log';

function writeLog($message)
{
    global $logFile;
    file_put_contents(
        $logFile,
        "[" . date("Y-m-d H:i:s") . "] " . $message . PHP_EOL,
        FILE_APPEND
    );
}

try {

    $dsn = "pgsql:host=$host;port=$port;dbname=$dbname";

    $pdo = new PDO($dsn, $user, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
    ]);

    writeLog("Connexion PostgreSQL réussie.");

    $sql = <<<SQL

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_commande') THEN
        CREATE TYPE status_commande AS ENUM ('payee','en_attente','annulee');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'statut_formation') THEN
        CREATE TYPE statut_formation AS ENUM ('active','inactive');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role_utilisateur') THEN
        CREATE TYPE role_utilisateur AS ENUM ('client','admin');
    END IF;
END
\$\$;

CREATE TABLE IF NOT EXISTS utilisateurs (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prenom VARCHAR(100) NOT NULL,

    nom VARCHAR(100) NOT NULL,

    email VARCHAR(150) UNIQUE NOT NULL,

    telephone VARCHAR(20),

    password VARCHAR(255) NOT NULL,

    role role_utilisateur DEFAULT 'client',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS formations (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    titre VARCHAR(255) NOT NULL,

    description TEXT,

    image VARCHAR(255),

    categorie VARCHAR(50) NOT NULL,

    prix NUMERIC(10,2) DEFAULT 0,

    duree INTEGER DEFAULT 0,

    statut statut_formation DEFAULT 'active',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commandes (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    utilisateur_id INTEGER NOT NULL,

    formation_id INTEGER NOT NULL,

    montant NUMERIC(10,2) NOT NULL,

    status status_commande DEFAULT 'en_attente',

    progression INTEGER DEFAULT 0,

    modules_done INTEGER DEFAULT 0,

    reference VARCHAR(50) UNIQUE,

    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    date_obtention TIMESTAMP,

    CONSTRAINT fk_utilisateur
        FOREIGN KEY(utilisateur_id)
        REFERENCES utilisateurs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_formation
        FOREIGN KEY(formation_id)
        REFERENCES formations(id)
        ON DELETE CASCADE
);

SQL;

    $pdo->exec($sql);

    writeLog("Tables créées avec succès.");

    echo "✅ Installation terminée.";

} catch (PDOException $e) {

    writeLog("ERREUR : " . $e->getMessage());

    http_response_code(500);

    echo "❌ Erreur lors de la création des tables.<br>";

    echo "Consultez le fichier : logs/database.log";
}